Travis: install specific hwloc version on OSX.
This commit compiles and installs hwloc 1.11.0, instead of installing it
via homebrew. The current version (2.0.1) in homebrew gives the following
error when statically linking LTSmin binaries.

undef: _clGetPlatformIDs
undef: _clGetDeviceIDs
undef: _clGetPlatformInfo
undef: _clGetDeviceInfo
Undefined symbols for architecture x86_64:
  "_clGetPlatformIDs", referenced from:
      _hwloc_opencl_discover in libhwloc.a(topology-opencl.o)
  "_clGetDeviceIDs", referenced from:
      _hwloc_opencl_discover in libhwloc.a(topology-opencl.o)
  "_clGetPlatformInfo", referenced from:
      _hwloc_opencl_discover in libhwloc.a(topology-opencl.o)
  "_clGetDeviceInfo", referenced from:
      _hwloc_opencl_discover in libhwloc.a(topology-opencl.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)